config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  put 'completed_assignment', to: 'assignments#completed', as: :completed_assignment
  get 'completed_most', to: 'users#show_completed', as: :completed_most
  # get 'users/:user_id/assignments', to: 'assignments#index', as: :assignments
  # get 'users/:user_id/assignments', to: 'assignments#show', as: :user_assignment

  resources :users, only: [:index, :show] do
    resources :assignments
  end

  resources :assignments do
    resources :tasks do
      member do
        patch :complete
      end
    end
  end

  root "welcome#index"
  get '*path' => redirect('/')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  has_many :assigned_tasks, dependent: :destroy
  has_many :tasks, through: :assigned_tasks

  validates_presence_of :name
  validates_presence_of :due_date


  def self.complete
    where(status: true).order('id DESC')
  end

  def complete?
    status
  end

  def self.incomplete
    where(status: false).order('id DESC')
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :assigned_tasks, dependent: :destroy
  has_many :assignments, through: :assigned_tasks

  validates_presence_of :name

  def completed?
    !completed_at.blank?
  end
end#class

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]

  #GET/ASSIGNMENTS
  def index
    user = User.find params[:user_id]
    @incomplete_assignments = user.assignments.incomplete
    @complete_assignments = user.assignments.complete
  end#index

  def new
    @assignment = current_user.assignments.build
    @assignment.tasks.build
  end#new

  #POST
  def create
    @assignment = current_user.assignments.build(assignment_params)
     if @assignment.save
       redirect_to [current_user, @assignment], notice: "Assignment was created successfully!"
     else
       render :new
     end
   end #create

   def show
      #@user = current_user.assignments
      @task = Task.new
    end#show

#PATCH
   def edit
   end

  def update
    @assignment.update(assignment_params)

    redirect_to [current_user, @assignment], notice: "Assignment updated successfully!"
  end#update


 #DELETE
  def destroy
    @assignment.destroy

    redirect_to [current_user, @assignment], notice: "Assignment was deleted successfully!"
  end #destroy

  def completed
    binding.pry
     Assignment.where(id: params[:assignment_ids]).update_all(status: true)
     current_user.assignments_completed_count +=(params[:assignment_ids].count)
     current_user.save

     redirect_to user_assignments_path(current_user.id)
  end#completed

   private
#STRONG PARAMS
   def set_assignment
     @assignment = Assignment.find(params[:id])
   end

   def assignment_params
     params.require(:assignment).permit(:name, :due_date, task_attributes: [:name])
   end

end#class

app/helpers/assignments_helper.rb
module AssignmentsHelper
  def completed
    if  @assignment.user != current_user

     redirect_to root_path, notice: "Not your assignments"
    else
     Assignment.where(id: params[:assignment_id]).update_all(status: true)

     redirect_to assignments_path
    end
  end#completed

end

app/views/assignments/_form.html.erb
<%= form_for([current_user, @assignment]) do |f| %>
   <% if @assignment.errors.any? %>
    <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this Assignment from being saved:</h2>
     <ul>
      <% @assignment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
      </ul>
      <% end %>
    <br><br>

<%= f.label :name %>
  <%= f.text_field :name %>
   <%= f.label :due_date %>
    <%= f.text_field :due_date %>
    <%=  f.hidden_field :user_id , :value => current_user.id %>

    <%= f.submit %>
  <% end %>

  <%= link_to 'Back to your assignments', user_assignments_path(current_user, @assignment) %>

app/views/assignments/edit.html.erb
<h1>Edit Assignment</h1>
	 <%= render 'form' %>


	 

app/views/assignments/index.html.erb
<center>
<br>
<div class="links">
  <%= link_to "Create New Assignment", new_assignment_path %>
</div>
<h3>Incomplete Assignments</h3>
  <%= form_tag(completed_assignment_path, method: :put) do %>
    <% for assignment in @incomplete_assignments %>
      <ul>
        <%= check_box_tag 'assignment_ids[]', assignment.id %>
        <%= link_to assignment.name, user_assignment_path(current_user, assignment) %>
      </ul>
    <% end %>
    <%= submit_tag 'Mark as Completed' %>
  <% end %>
<br>
</center>
<center>
<h3>Completed Assignments</h3>
  <% for assignment in @complete_assignments %>
    <ul>
     <%= link_to assignment.name, assignment_path(assignment) %>
    </ul>
 <%# end %>
<% end %>
</center>


<h2> Curious to see <%= link_to "Current Stats", completed_most_path(@user) %> ?</h2>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>
  <%= render 'form' %>

app/views/assignments/show.html.erb
<h2>Created by: <%= @assignment.user.email %></h2>
<br><br>
<h2><%= @assignment.name %></h2>
<h4>Due Date: <%= @assignment.due_date %></h4>

<div class="tasks_wrapper">
  <%= render @assignment.tasks %>
</div>
<% if @assignment.user == current_user %>
 <div class="form">
	<%= render "tasks/form" %>
</div>
<div class="links">
   <%= link_to 'Delete Assignment', [current_user, @assignment], method: :delete, data: { confirm: "Are you sure?" } %>
  <br>
   <%= link_to 'Edit Assignment', [:edit, current_user, @assignment] %>
  <br>
   <%= link_to 'Back to Assignments', [current_user, :assignments] %>
   <br>
</div>
<% else %>
<%= link_to 'Back to Assignments', assignments_path(@assignment) %>
<% end %>